export const INCREMENT_ACTION = "INCREMENT_ACTION";

export const DECREMENT_ACTION = "DECREMENT_ACTION";

export const POST_USER_LOGIN_ACTION = "POST_USER_LOGIN_ACTION";

export const SAGA_LOGIN_ACTION = "SAGA_LOGIN_ACTION";

export const FETCH_DASHBOARD_DATA_ACTION = "FETCH_DASHBOARD_DATA_ACTION";

export const FETCH_DASHBOARD_DATA_ACTION_SUCCESS =
  "FETCH_DASHBOARD_DATA_ACTION_SUCCESS";

export const GET_SETTINGS_ACTION = "GET_SETTINGS_ACTION";

export const GET_SETTINGS_ACTION_SUCCESS = "GET_SETTINGS_ACTION_SUCCESS";
