export const INCREMENT = "INCREMENT";

export const DECREMENT = "DECREMENT";

export const LOGIN = "LOGIN";

export const SAGA_LOGIN = "SAGA_LOGIN";

export const DASHBOARD_DATA = "DASHBOARD_DATA";

export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";

export const GET_SETTINGS = "GET_SETTINGS";

export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
